<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach ($this->data() as $item){
               City::create($item);
        }
    }


    public function data()
    {
        return [
           [ 'province_id' => 1 , 'name' => 'آذرشهر'],
           [ 'province_id' => 1 , 'name' => 'اسكو'],
           [ 'province_id' => 1 , 'name' => 'اهر'],
           [ 'province_id' => 1 , 'name' => 'بستان آباد'],
           [ 'province_id' => 1  , 'name' => 'بناب'],
           [ 'province_id' => 1 , 'name' => 'تبريز'],
           [ 'province_id' => 1 , 'name' => 'جلفا'],
           [ 'province_id' => 1 , 'name' => 'چار اويماق'],
           [ 'province_id' => 1 , 'name' => 'سراب'],
           [ 'province_id' => 1 , 'name' => 'شبستر'],
           [ 'province_id' => 1 , 'name' => 'عجبشير'],
           [ 'province_id' => 1 , 'name' => 'كليبر'],
           [ 'province_id' => 1 , 'name' => 'مراغه'],
           [ 'province_id' => 1 , 'name' => 'مرند'],
           [ 'province_id' => 1 , 'name' => 'ملكان'],
           [ 'province_id' => 1 , 'name' => 'ميانه'],
           [ 'province_id' => 1 , 'name' => 'ورزقان'],
           [ 'province_id' => 1 , 'name' => 'هريس'],
           [ 'province_id' => 1 , 'name' => 'هشترود'],

           [ 'province_id' => 2 , 'name' => 'اروميه'],
           [ 'province_id' => 2 , 'name' => 'اشنويه'],
           [ 'province_id' => 2 , 'name' => 'بوكان'],
           [ 'province_id' => 2 , 'name' => 'پير انشهر'],
           [ 'province_id' => 2 , 'name' => 'تكاب'],
           [ 'province_id' => 2 , 'name' => 'چالدران'],
           [ 'province_id' => 2 , 'name' => 'خوي'],
           [ 'province_id' => 2 , 'name' => 'سردشت'],
           [ 'province_id' => 2 , 'name' => 'سلماس'],
           [ 'province_id' => 2 , 'name' => 'شاهين دژ'],
           [ 'province_id' => 2 , 'name' => 'ماكو'],
           [ 'province_id' => 2 , 'name' => 'مهاباد'],
           [ 'province_id' => 2 , 'name' => 'مياندوآب'],
           [ 'province_id' => 2 , 'name' => 'نقده'],

           [ 'province_id' => 3 , 'name' => 'اردبيل'],
           [ 'province_id' => 3 , 'name' => 'بيله سوار'],
           [ 'province_id' => 3 , 'name' => 'پارس آباد'],
           [ 'province_id' => 3 , 'name' => 'خلخال'],
           [ 'province_id' => 3 , 'name' => 'كوثر'],
           [ 'province_id' => 3 , 'name' => 'گرمي'],
           [ 'province_id' => 3 , 'name' => 'مشگين'],
           [ 'province_id' => 3 , 'name' => 'نمين'],
           [ 'province_id' => 3 , 'name' => 'نير'],


           [ 'province_id' => 4 , 'name' => 'آران و بيدگل'],
           [ 'province_id' => 4 , 'name' => 'اردستان'],
           [ 'province_id' => 4 , 'name' => 'اصفهان'],
           [ 'province_id' => 4 , 'name' => 'برخوار و ميمه'],
           [ 'province_id' => 4 , 'name' => 'تيران و كرون'],
           [ 'province_id' => 4 , 'name' => 'چادگان'],
           [ 'province_id' => 4 , 'name' => 'خميني شهر'],
           [ 'province_id' => 4 , 'name' => 'خوانسار'],
           [ 'province_id' => 4 , 'name' => 'سميرم'],
           [ 'province_id' => 4 , 'name' => 'شاهين شهر و ميمه'],
           [ 'province_id' => 4 , 'name' => 'شهر رضا'],
           [ 'province_id' => 4 , 'name' => 'سميرم سفلي'],
           [ 'province_id' => 4 , 'name' => 'فريدن'],
           [ 'province_id' => 4 , 'name' => 'فريدون شهر'],
           [ 'province_id' => 4 , 'name' => 'فلاورجان'],
           [ 'province_id' => 4 , 'name' => 'كاشان'],
           [ 'province_id' => 4 , 'name' => 'گلپايگان'],
           [ 'province_id' => 4 , 'name' => 'لنجان'],
           [ 'province_id' => 4 , 'name' => 'نائين'],
           [ 'province_id' => 4 , 'name' => 'نجف آباد'],
           [ 'province_id' => 4 , 'name' => 'نطنز'],


           [ 'province_id' => 5 , 'name' => 'ساوجبلاق'],
           [ 'province_id' => 5 , 'name' => 'كرج'],
           [ 'province_id' => 5 , 'name' => 'نظرآباد'],
           [ 'province_id' => 5 , 'name' => 'طالقان'],


           [ 'province_id' => 6 , 'name' => 'آبدانان'],
           [ 'province_id' => 6 , 'name' => 'ايلام'],
           [ 'province_id' => 6 , 'name' => 'ايوان'],
           [ 'province_id' => 6 , 'name' => 'دره شهر'],
           [ 'province_id' => 6 , 'name' => 'دهلران'],
           [ 'province_id' => 6 , 'name' => 'شيران و چرداول'],
           [ 'province_id' => 6 , 'name' => 'مهران'],

           [ 'province_id' => 7 , 'name' => 'بوشهر'],
           [ 'province_id' => 7 , 'name' => 'تنگستان'],
           [ 'province_id' => 7 , 'name' => 'جم'],
           [ 'province_id' => 7 , 'name' => 'دشتستان'],
           [ 'province_id' => 7 , 'name' => 'دشتي'],
           [ 'province_id' => 7 , 'name' => 'دير'],
           [ 'province_id' => 7 , 'name' => 'ديلم'],
           [ 'province_id' => 7 , 'name' => 'كنگان'],
           [ 'province_id' => 7 , 'name' => 'گناوه'],

           [ 'province_id' => 8 , 'name' => 'اسلام شهر'],
           [ 'province_id' => 8 , 'name' => 'پاكدشت'],
           [ 'province_id' => 8 , 'name' => 'تهران'],
           [ 'province_id' => 8 , 'name' => 'دماوند'],
           [ 'province_id' => 8 , 'name' => 'رباط كريم'],
           [ 'province_id' => 8 , 'name' => 'ري'],
           [ 'province_id' => 8 , 'name' => 'شميرانات'],
           [ 'province_id' => 8 , 'name' => 'شهريار'],
           [ 'province_id' => 8 , 'name' => 'فيروزكوه'],
           [ 'province_id' => 8 , 'name' => 'ورامين'],

           [ 'province_id' => 9 , 'name' => 'اردل'],
           [ 'province_id' => 9 , 'name' => 'بروجن'],
           [ 'province_id' => 9 , 'name' => 'شهركرد'],
           [ 'province_id' => 9 , 'name' => 'فارسان'],
           [ 'province_id' => 9 , 'name' => 'كوهرنگ'],
           [ 'province_id' => 9 , 'name' => 'لردگان'],

           [ 'province_id' => 10 , 'name' => 'بيرجند'],
           [ 'province_id' => 10 , 'name' => 'درميان'],
           [ 'province_id' => 10 , 'name' => 'سرايان'],
           [ 'province_id' => 10 , 'name' => 'سر بيشه'],
           [ 'province_id' => 10 , 'name' => 'فردوس'],
           [ 'province_id' => 10 , 'name' => 'قائن'],
           [ 'province_id' => 10 , 'name' => 'نهبندان'],

           [ 'province_id' => 11 , 'name' => 'برد سكن'],
           [ 'province_id' => 11 , 'name' => 'بجستان'],
           [ 'province_id' => 11 , 'name' => 'تايباد'],
           [ 'province_id' => 11 , 'name' => 'تحت جلگه'],
           [ 'province_id' => 11 , 'name' => 'تربت جام'],
           [ 'province_id' => 11 , 'name' => 'تربت حيدريه'],
           [ 'province_id' => 11 , 'name' => 'چناران'],
           [ 'province_id' => 11 , 'name' => 'جغتاي'],
           [ 'province_id' => 11 , 'name' => 'جوين'],
           [ 'province_id' => 11 , 'name' => 'خليل آباد'],
           [ 'province_id' => 11 , 'name' => 'خواف'],
           [ 'province_id' => 11 , 'name' => 'درگز'],
           [ 'province_id' => 11 , 'name' => 'رشتخوار'],
           [ 'province_id' => 11 , 'name' => 'زاوه'],
           [ 'province_id' => 11 , 'name' => 'سبزوار'],
           [ 'province_id' => 11 , 'name' => 'سرخس'],
           [ 'province_id' => 11 , 'name' => 'فريمان'],
           [ 'province_id' => 11 , 'name' => 'قوچان'],
           [ 'province_id' => 11 , 'name' => 'طرقبه و شانديز'],
           [ 'province_id' => 11 , 'name' => 'كاشمر'],
           [ 'province_id' => 11 , 'name' => 'كلات'],
           [ 'province_id' => 11 , 'name' => 'گناباد'],
           [ 'province_id' => 11 , 'name' => 'مشهد'],
           [ 'province_id' => 11 , 'name' => 'مه ولات'],

           [ 'province_id' => 12 , 'name' => 'اسفراين'],
           [ 'province_id' => 12 , 'name' => 'بجنورد'],
           [ 'province_id' => 12 , 'name' => 'جاجرم'],
           [ 'province_id' => 12 , 'name' => 'شيروان'],
           [ 'province_id' => 12 , 'name' => 'فاروج'],
           [ 'province_id' => 12 , 'name' => 'مانه و سملقان'],

            [ 'province_id' => 13 , 'name' => ''],
            [ 'province_id' => 13 , 'name' => 'آبادان'],
            [ 'province_id' => 13 , 'name' => 'اميديه'],
            [ 'province_id' => 13 , 'name' => 'انديمشك'],
            [ 'province_id' => 13 , 'name' => 'اهواز'],
            [ 'province_id' => 13 , 'name' => 'ايذه'],
            [ 'province_id' => 13 , 'name' => 'باغ ملك'],
            [ 'province_id' => 13 , 'name' => 'بندرماهشهر'],
            [ 'province_id' => 13 , 'name' => 'بهبهان'],
            [ 'province_id' => 13 , 'name' => 'خرمشهر'],
            [ 'province_id' => 13 , 'name' => 'دزفول'],
            [ 'province_id' => 13 , 'name' => 'دشت آزادگان'],
            [ 'province_id' => 13 , 'name' => 'رامشير'],
            [ 'province_id' => 13 , 'name' => 'رامهرمز'],
            [ 'province_id' => 13 , 'name' => 'شادگان'],
            [ 'province_id' => 13 , 'name' => 'شوش'],
            [ 'province_id' => 13 , 'name' => 'شوشتر'],
            [ 'province_id' => 13 , 'name' => 'گتوند'],
            [ 'province_id' => 13 , 'name' => 'لالي'],
            [ 'province_id' => 13 , 'name' => 'مسجد سليمان'],

            [ 'province_id' => 14 , 'name' => 'ابهر'],
            [ 'province_id' => 14 , 'name' => 'ايجرود'],
            [ 'province_id' => 14 , 'name' => 'خدابنده'],
            [ 'province_id' => 14 , 'name' => 'خرمدره'],
            [ 'province_id' => 14 , 'name' => 'زنجان'],
            [ 'province_id' => 14 , 'name' => 'طارم'],
            [ 'province_id' => 14 , 'name' => 'ماه نشان'],

            [ 'province_id' => 15 , 'name' => 'دامغان'],
            [ 'province_id' => 15 , 'name' => 'سمنان'],
            [ 'province_id' => 15 , 'name' => 'شاهرود'],
            [ 'province_id' => 15 , 'name' => 'گرمسار'],
            [ 'province_id' => 15 , 'name' => 'مهدي شهر'],

            [ 'province_id' => 16 , 'name' => 'ايرانشهر'],
            [ 'province_id' => 16 , 'name' => 'چابهار'],
            [ 'province_id' => 16 , 'name' => 'خاش'],
            [ 'province_id' => 16 , 'name' => 'دلگان'],
            [ 'province_id' => 16 , 'name' => 'زابل'],
            [ 'province_id' => 16 , 'name' => 'زاهدان'],
            [ 'province_id' => 16 , 'name' => 'زهك'],
            [ 'province_id' => 16 , 'name' => 'سراوان'],
            [ 'province_id' => 16 , 'name' => 'سرباز'],
            [ 'province_id' => 16 , 'name' => 'كنارك'],
            [ 'province_id' => 16 , 'name' => 'نيكشهر'],

            [ 'province_id' => 17 , 'name' => 'آباده'],
            [ 'province_id' => 17 , 'name' => 'ارسنجان'],
            [ 'province_id' => 17 , 'name' => 'استهبان'],
            [ 'province_id' => 17 , 'name' => 'اقليد'],
            [ 'province_id' => 17 , 'name' => 'بوانات'],
            [ 'province_id' => 17 , 'name' => 'پاسارگاد'],
            [ 'province_id' => 17 , 'name' => 'جهرم'],
            [ 'province_id' => 17 , 'name' => 'خرم بيد'],
            [ 'province_id' => 17 , 'name' => 'خنج'],
            [ 'province_id' => 17 , 'name' => 'داراب'],
            [ 'province_id' => 17 , 'name' => 'زرين دشت'],
            [ 'province_id' => 17 , 'name' => 'سپيدان'],
            [ 'province_id' => 17 , 'name' => 'شيراز'],
            [ 'province_id' => 17 , 'name' => 'فراشبند'],
            [ 'province_id' => 17 , 'name' => 'فسا'],
            [ 'province_id' => 17 , 'name' => 'فيروزآباد'],
            [ 'province_id' => 17 , 'name' => 'قير و كارزين'],
            [ 'province_id' => 17 , 'name' => 'كازرون'],
            [ 'province_id' => 17 , 'name' => 'لارستان'],
            [ 'province_id' => 17 , 'name' => 'لامرد'],
            [ 'province_id' => 17 , 'name' => 'مرودشت'],
            [ 'province_id' => 17 , 'name' => 'ممسني'],
            [ 'province_id' => 17 , 'name' => 'مهر'],
            [ 'province_id' => 17 , 'name' => 'ني ريز'],

            [ 'province_id' => 18 , 'name' => 'آبيك'],
            [ 'province_id' => 18 , 'name' => 'البرز'],
            [ 'province_id' => 18 , 'name' => 'بوئين زهرا'],
            [ 'province_id' => 18 , 'name' => 'تاكستان'],
            [ 'province_id' => 18 , 'name' => 'قزوين'],

            [ 'province_id' => 19 , 'name' => 'قم'],

            [ 'province_id' => 20 , 'name' => 'بانه'],
            [ 'province_id' => 20 , 'name' => 'بيجار'],
            [ 'province_id' => 20 , 'name' => 'ديواندره'],
            [ 'province_id' => 20 , 'name' => 'سروآباد'],
            [ 'province_id' => 20 , 'name' => 'سقز'],
            [ 'province_id' => 20 , 'name' => 'سنندج'],
            [ 'province_id' => 20 , 'name' => 'قروه'],
            [ 'province_id' => 20 , 'name' => 'كامياران'],
            [ 'province_id' => 20 , 'name' => 'مريوان'],

            [ 'province_id' => 21 , 'name' => 'بافت'],
            [ 'province_id' => 21 , 'name' => 'بردسير'],
            [ 'province_id' => 21 , 'name' => 'بم'],
            [ 'province_id' => 21 , 'name' => 'جيرفت'],
            [ 'province_id' => 21 , 'name' => 'راور'],
            [ 'province_id' => 21 , 'name' => 'رفسنجان'],
            [ 'province_id' => 21 , 'name' => 'رودبار جنوب'],
            [ 'province_id' => 21 , 'name' => 'زرند'],
            [ 'province_id' => 21 , 'name' => 'سيرجان'],
            [ 'province_id' => 21 , 'name' => 'شهر بابك'],
            [ 'province_id' => 21 , 'name' => 'عنبرآباد'],
            [ 'province_id' => 21 , 'name' => 'قلعه گنج'],
            [ 'province_id' => 21 , 'name' => 'كرمان'],
            [ 'province_id' => 21 , 'name' => 'كوهبنان'],
            [ 'province_id' => 21 , 'name' => 'كهنوج'],
            [ 'province_id' => 21 , 'name' => 'منوجان'],

            [ 'province_id' => 22 , 'name' => 'اسلام آباد غرب'],
            [ 'province_id' => 22 , 'name' => 'پاوه'],
            [ 'province_id' => 22 , 'name' => 'ثلاث باباجاني'],
            [ 'province_id' => 22 , 'name' => 'جوانرود'],
            [ 'province_id' => 22 , 'name' => 'دالاهو'],
            [ 'province_id' => 22 , 'name' => 'روانسر'],
            [ 'province_id' => 22 , 'name' => 'سر پل ذهاب'],
            [ 'province_id' => 22 , 'name' => 'سنقر'],
            [ 'province_id' => 22 , 'name' => 'صحنه'],
            [ 'province_id' => 22 , 'name' => 'قصر شيرين'],
            [ 'province_id' => 22 , 'name' => 'كرمانشاه'],
            [ 'province_id' => 22 , 'name' => 'كنگاور'],
            [ 'province_id' => 22 , 'name' => 'گيلان غرب'],
            [ 'province_id' => 22 , 'name' => 'هرسين'],

            [ 'province_id' => 23 , 'name' => 'بوير احمد'],
            [ 'province_id' => 23 , 'name' => 'بهمئي'],
            [ 'province_id' => 23 , 'name' => 'دنا'],
            [ 'province_id' => 23 , 'name' => 'كهگيلويه'],
            [ 'province_id' => 23 , 'name' => 'گچساران'],

            [ 'province_id' => 24 , 'name' => 'آزادشهر'],
            [ 'province_id' => 24 , 'name' => 'آق قلا'],
            [ 'province_id' => 24 , 'name' => 'بندر گز'],
            [ 'province_id' => 24 , 'name' => 'بندر تركمن'],
            [ 'province_id' => 24 , 'name' => 'راميان'],
            [ 'province_id' => 24 , 'name' => 'علي آباد'],
            [ 'province_id' => 24 , 'name' => 'كرد كوي'],
            [ 'province_id' => 24 , 'name' => 'كلاله'],
            [ 'province_id' => 24 , 'name' => 'گرگان'],
            [ 'province_id' => 24 , 'name' => 'گنبد كاووس'],
            [ 'province_id' => 24 , 'name' => 'مينو دشت'],

            [ 'province_id' => 25 , 'name' => 'آستارا'],
            [ 'province_id' => 25 , 'name' => 'آستانه اشرفيه'],
            [ 'province_id' => 25 , 'name' => 'املش'],
            [ 'province_id' => 25 , 'name' => 'بندر انزلي'],
            [ 'province_id' => 25 , 'name' => 'رشت'],
            [ 'province_id' => 25 , 'name' => 'رضوانشهر'],
            [ 'province_id' => 25 , 'name' => 'رودبار'],
            [ 'province_id' => 25 , 'name' => 'رودسر'],
            [ 'province_id' => 25 , 'name' => 'سياهكل'],
            [ 'province_id' => 25 , 'name' => 'شفت'],
            [ 'province_id' => 25 , 'name' => 'صومعه سرا'],
            [ 'province_id' => 25 , 'name' => 'طوالش'],
            [ 'province_id' => 25 , 'name' => 'فومن'],
            [ 'province_id' => 25 , 'name' => 'لاهيجان'],
            [ 'province_id' => 25 , 'name' => 'لنگرود'],
            [ 'province_id' => 25 , 'name' => 'ماسال'],

            [ 'province_id' => 26 , 'name' => 'ازنا'],
            [ 'province_id' => 26 , 'name' => 'اليگودرز'],
            [ 'province_id' => 26 , 'name' => 'بروجرد'],
            [ 'province_id' => 26 , 'name' => 'پلدختر'],
            [ 'province_id' => 26 , 'name' => 'خرم آباد'],
            [ 'province_id' => 26 , 'name' => 'دورود'],
            [ 'province_id' => 26 , 'name' => 'دلفان'],
            [ 'province_id' => 26 , 'name' => 'سلسله'],
            [ 'province_id' => 26 , 'name' => 'كوهدشت'],
            [ 'province_id' => 26 , 'name' => 'الشتر'],
            [ 'province_id' => 26 , 'name' => 'نورآباد'],

            [ 'province_id' => 27 , 'name' => 'آمل'],
            [ 'province_id' => 27 , 'name' => 'بابل'],
            [ 'province_id' => 27 , 'name' => 'بابلسر'],
            [ 'province_id' => 27 , 'name' => 'بهشهر'],
            [ 'province_id' => 27 , 'name' => 'تنكابن'],
            [ 'province_id' => 27 , 'name' => 'جويبار'],
            [ 'province_id' => 27 , 'name' => 'چالوس'],
            [ 'province_id' => 27 , 'name' => 'رامسر'],
            [ 'province_id' => 27 , 'name' => 'ساري'],
            [ 'province_id' => 27 , 'name' => 'سوادكوه'],
            [ 'province_id' => 27 , 'name' => 'قائم شهر'],
            [ 'province_id' => 27 , 'name' => 'گلوگاه'],
            [ 'province_id' => 27 , 'name' => 'محمود آباد'],
            [ 'province_id' => 27 , 'name' => 'نكا'],
            [ 'province_id' => 27 , 'name' => 'نور'],
            [ 'province_id' => 27 , 'name' => 'نوشهر'],
            [ 'province_id' => 27 , 'name' => 'فريدونكنار'],

            [ 'province_id' => 28 , 'name' => 'آشتيان'],
            [ 'province_id' => 28 , 'name' => 'اراك'],
            [ 'province_id' => 28 , 'name' => 'تفرش'],
            [ 'province_id' => 28 , 'name' => 'خمين'],
            [ 'province_id' => 28 , 'name' => 'دليجان'],
            [ 'province_id' => 28 , 'name' => 'زرنديه'],
            [ 'province_id' => 28 , 'name' => 'ساوه'],
            [ 'province_id' => 28 , 'name' => 'شازند'],
            [ 'province_id' => 28 , 'name' => 'كميجان'],
            [ 'province_id' => 28 , 'name' => 'محلات'],

            [ 'province_id' => 29 , 'name' => 'بندرعباس'],
            [ 'province_id' => 29 , 'name' => 'ميناب'],
            [ 'province_id' => 29 , 'name' => 'بندر لنگه'],
            [ 'province_id' => 29 , 'name' => 'رودان-دهبارز'],
            [ 'province_id' => 29 , 'name' => 'جاسك'],
            [ 'province_id' => 29 , 'name' => 'قشم'],
            [ 'province_id' => 29 , 'name' => 'حاجي آباد'],
            [ 'province_id' => 29 , 'name' => 'ابوموسي'],
            [ 'province_id' => 29 , 'name' => 'بستك'],
            [ 'province_id' => 29 , 'name' => 'گاوبندي'],
            [ 'province_id' => 29 , 'name' => 'خمير'],

            [ 'province_id' => 30 , 'name' => 'اسدآباد'],
            [ 'province_id' => 30 , 'name' => 'بهار'],
            [ 'province_id' => 30 , 'name' => 'تويسركان'],
            [ 'province_id' => 30 , 'name' => 'رزن'],
            [ 'province_id' => 30 , 'name' => 'كبودر آهنگ'],
            [ 'province_id' => 30 , 'name' => 'ملاير'],
            [ 'province_id' => 30 , 'name' => 'نهاوند'],
            [ 'province_id' => 30 , 'name' => 'همدان'],

            [ 'province_id' => 31 , 'name' => 'ابركوه'],
            [ 'province_id' => 31 , 'name' => 'اردكان'],
            [ 'province_id' => 31 , 'name' => 'بافق'],
            [ 'province_id' => 31 , 'name' => 'تفت'],
            [ 'province_id' => 31 , 'name' => 'خاتم'],
            [ 'province_id' => 31 , 'name' => 'صدوق'],
            [ 'province_id' => 31 , 'name' => 'طبس'],
            [ 'province_id' => 31 , 'name' => 'مهريز'],
            [ 'province_id' => 31 , 'name' => 'ميبد'],
            [ 'province_id' => 31 , 'name' => 'يزد'],

        ];
    }
}
